#!/usr/bin/env bash

set -e
set -o pipefail

[[ -z "${KUBE_FZF_PATH}" ]] && source kube-fzf.sh || source $KUBE_FZF_PATH

describepod() {
  local context namespace pod_query result namespace pod_name

  _kube_fzf_handler "describepod" "$@"
  context=$(echo $args | awk -F '|' '{ print $1 }')
  namespace=$(echo $args | awk -F '|' '{ print $2 }')
  if [[ -z $namespace ]]
  then if [[ $context -eq "minikube" ]]
       then
           namespace='default'
       else
           namespace=$context
       fi
  fi
  pod_query=$(echo $args | awk -F '|' '{ print $3 }')

  pod_name=$(_kube_fzf_search_pod "$context" "$namespace" "$pod_query")

  _kube_fzf_echo "kubectl describe pod $pod_name --context='$context' --namespace='$namespace'"
  kubectl describe pod $pod_name --context=$context --namespace=$namespace
}

describepod "$@"
