#!/usr/bin/env bash

set -e
set -o pipefail

[[ -z "${KUBE_FZF_PATH}" ]] && source kube-fzf.sh || source $KUBE_FZF_PATH

findpod() {
  local context namespace pod_query result namespace pod_name

  _kube_fzf_handler "findpod" "$@"
  context=$(echo $args | awk -F '|' '{ print $1 }')
  namespace=$(echo $args | awk -F '|' '{ print $2 }')
  [ -z $namespace ] && namespace=$context
  pod_query=$(echo $args | awk -F '|' '{ print $3 }')

  result=$(_kube_fzf_search_pod "$context" "$namespace" "$pod_query")
  IFS=$'|' read -r namespace pod_name <<< "$result"

  _kube_fzf_echo "kubectl get pod --context='$context' --namespace='$namespace' --output=wide $pod_name"
  kubectl get pod --context=$context --namespace=$namespace --output=wide $pod_name
}

findpod "$@"
