#!/usr/bin/env bash

set -e
set -o pipefail

[[ -z "${KUBE_FZF_PATH}" ]] && source kube-fzf.sh || source $KUBE_FZF_PATH

tailpod() {
  local context namespace pod_query result namespace pod_name

  _kube_fzf_handler "tailpod" "$@"
  context=$(echo $args | awk -F '|' '{ print $1 }')
  namespace=$(echo $args | awk -F '|' '{ print $2 }')
  [ -z $namespace ] && namespace=$context
  pod_query=$(echo $args | awk -F '|' '{ print $3 }')

  pod_name=$(_kube_fzf_search_pod "$context" "$namespace" "$pod_query")

  local fzf_args=$(_kube_fzf_fzf_args "" "--select-1")
  local container_name=$(kubectl get pod $pod_name --context=$context --namespace=$namespace --output=jsonpath='{.spec.containers[*].name}' \
    | tr ' ' '\n' \
    | fzf $(echo $fzf_args))

  _kube_fzf_echo "kubectl logs --context='$context' --namespace='$namespace' --follow $pod_name -c $container_name"
  kubectl logs --context=$context --namespace=$namespace --follow $pod_name -c $container_name
}

tailpod "$@"
